-- Add composite score columns to models table
ALTER TABLE models ADD COLUMN IF NOT EXISTS intelligence_score DECIMAL(5, 2) DEFAULT 0;
ALTER TABLE models ADD COLUMN IF NOT EXISTS speed_score DECIMAL(5, 2) DEFAULT 0;
ALTER TABLE models ADD COLUMN IF NOT EXISTS value_score DECIMAL(5, 2) DEFAULT 0;
ALTER TABLE models ADD COLUMN IF NOT EXISTS overall_score DECIMAL(5, 2) DEFAULT 0;
ALTER TABLE models ADD COLUMN IF NOT EXISTS scores_last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW();
